#!/bin/bash

#
#	A typical invocation of dig looks like:
#
#	dig @server name type
#
#	where:
#
#	server
#		is the name or IP address of the name server to query.
#		This can be an IPv4 address in dotted-decimal notation or
#		an IPv6 address in colon-delimited notation.
#		When the supplied server argument is a hostname,
#		dig resolves that name before querying that name server.
#		If no server argument is provided, dig consults /etc/resolv.conf and
#		queries the name servers listed there. The reply
#		from the name server that responds is displayed.
#
#	name
#		is the name of the resource record that is to be looked up.
#
#	type
#		indicates what type of query is required -- ANY, A, MX, SIG, etc.
#		type can be any valid query type. If no type argument is supplied,
#		dig will perform a lookup for an A record.
#

dig @8.8.8.8 slash16.org A
