#!/bin/bash

#
#	=============================
#	13.32.16.243
#	Amazon AWS Network Operations
#	=============================
#	13.32.16.91
#	Amazon AWS Network Operations
#	=============================
#	13.32.16.132
#	Amazon AWS Network Operations
#	=============================
#	13.32.16.222
#	Amazon AWS Network Operations
#	=============================
#	13.32.16.14
#	Amazon AWS Network Operations
#	=============================
#	13.32.16.42
#	Amazon AWS Network Operations
#	=============================
#	13.32.16.161
#	Amazon AWS Network Operations
#	=============================
#	13.32.16.167
#	Amazon AWS Network Operations
#

#
#	for i in $(dig +short slash16.org A)
#	do
#		echo "============================="
#		echo $i
#		whois $i | grep "OrgNOCName: " | sed 's/OrgNOCName:   //'
#	done
#
